/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			KBVector3 Account_position_defval = new KBVector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			KBVector3 Account_direction_defval = new KBVector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			List<DATATYPE_BASE> pAccount_onReqAvatarList_args = new List<DATATYPE_BASE>();
			pAccount_onReqAvatarList_args.Add(EntityDef.id2datatypes[10]);

			Method pAccount_onReqAvatarList = new Method();
			pAccount_onReqAvatarList.name = "onReqAvatarList";
			pAccount_onReqAvatarList.methodUtype = 5;
			pAccount_onReqAvatarList.aliasID = 1;
			pAccount_onReqAvatarList.args = pAccount_onReqAvatarList_args;

			pAccountModule.methods["onReqAvatarList"] = pAccount_onReqAvatarList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqAvatarList.aliasID] = pAccount_onReqAvatarList;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqAvatarList / 5).");

			List<DATATYPE_BASE> pAccount_onReqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onReqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onReqCreateAvatar_args.Add(EntityDef.id2datatypes[10]);

			Method pAccount_onReqCreateAvatar = new Method();
			pAccount_onReqCreateAvatar.name = "onReqCreateAvatar";
			pAccount_onReqCreateAvatar.methodUtype = 6;
			pAccount_onReqCreateAvatar.aliasID = 2;
			pAccount_onReqCreateAvatar.args = pAccount_onReqCreateAvatar_args;

			pAccountModule.methods["onReqCreateAvatar"] = pAccount_onReqCreateAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqCreateAvatar.aliasID] = pAccount_onReqCreateAvatar;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqCreateAvatar / 6).");

			List<DATATYPE_BASE> pAccount_onReqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onReqRemoveAvatar_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onReqRemoveAvatar_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_onReqRemoveAvatar = new Method();
			pAccount_onReqRemoveAvatar.name = "onReqRemoveAvatar";
			pAccount_onReqRemoveAvatar.methodUtype = 7;
			pAccount_onReqRemoveAvatar.aliasID = 3;
			pAccount_onReqRemoveAvatar.args = pAccount_onReqRemoveAvatar_args;

			pAccountModule.methods["onReqRemoveAvatar"] = pAccount_onReqRemoveAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqRemoveAvatar.aliasID] = pAccount_onReqRemoveAvatar;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqRemoveAvatar / 7).");

			List<DATATYPE_BASE> pAccount_reqAvatarEnterGame_args = new List<DATATYPE_BASE>();
			pAccount_reqAvatarEnterGame_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqAvatarEnterGame = new Method();
			pAccount_reqAvatarEnterGame.name = "reqAvatarEnterGame";
			pAccount_reqAvatarEnterGame.methodUtype = 3;
			pAccount_reqAvatarEnterGame.aliasID = -1;
			pAccount_reqAvatarEnterGame.args = pAccount_reqAvatarEnterGame_args;

			pAccountModule.methods["reqAvatarEnterGame"] = pAccount_reqAvatarEnterGame; 
			pAccountModule.base_methods["reqAvatarEnterGame"] = pAccount_reqAvatarEnterGame;

			pAccountModule.idbase_methods[pAccount_reqAvatarEnterGame.methodUtype] = pAccount_reqAvatarEnterGame;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarEnterGame / 3).");

			List<DATATYPE_BASE> pAccount_reqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqAvatarList = new Method();
			pAccount_reqAvatarList.name = "reqAvatarList";
			pAccount_reqAvatarList.methodUtype = 1;
			pAccount_reqAvatarList.aliasID = -1;
			pAccount_reqAvatarList.args = pAccount_reqAvatarList_args;

			pAccountModule.methods["reqAvatarList"] = pAccount_reqAvatarList; 
			pAccountModule.base_methods["reqAvatarList"] = pAccount_reqAvatarList;

			pAccountModule.idbase_methods[pAccount_reqAvatarList.methodUtype] = pAccount_reqAvatarList;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarList / 1).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 2;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 2).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatar_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqRemoveAvatar = new Method();
			pAccount_reqRemoveAvatar.name = "reqRemoveAvatar";
			pAccount_reqRemoveAvatar.methodUtype = 4;
			pAccount_reqRemoveAvatar.aliasID = -1;
			pAccount_reqRemoveAvatar.args = pAccount_reqRemoveAvatar_args;

			pAccountModule.methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar; 
			pAccountModule.base_methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatar.methodUtype] = pAccount_reqRemoveAvatar;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatar / 4).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[4] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			KBVector3 Avatar_position_defval = new KBVector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			KBVector3 Avatar_direction_defval = new KBVector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_HP = new Property();
			pAvatar_HP.name = "HP";
			pAvatar_HP.properUtype = 7;
			pAvatar_HP.properFlags = 4;
			pAvatar_HP.aliasID = 4;
			Int32 Avatar_HP_defval;
			Int32.TryParse("100", out Avatar_HP_defval);
			pAvatar_HP.defaultVal = Avatar_HP_defval;
			pAvatarModule.propertys["HP"] = pAvatar_HP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP.aliasID] = pAvatar_HP;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP / 7).");

			Property pAvatar_HP_Max = new Property();
			pAvatar_HP_Max.name = "HP_Max";
			pAvatar_HP_Max.properUtype = 8;
			pAvatar_HP_Max.properFlags = 4;
			pAvatar_HP_Max.aliasID = 5;
			Int32 Avatar_HP_Max_defval;
			Int32.TryParse("100", out Avatar_HP_Max_defval);
			pAvatar_HP_Max.defaultVal = Avatar_HP_Max_defval;
			pAvatarModule.propertys["HP_Max"] = pAvatar_HP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP_Max.aliasID] = pAvatar_HP_Max;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP_Max / 8).");

			Property pAvatar_MP = new Property();
			pAvatar_MP.name = "MP";
			pAvatar_MP.properUtype = 9;
			pAvatar_MP.properFlags = 4;
			pAvatar_MP.aliasID = 6;
			Int32 Avatar_MP_defval;
			Int32.TryParse("120", out Avatar_MP_defval);
			pAvatar_MP.defaultVal = Avatar_MP_defval;
			pAvatarModule.propertys["MP"] = pAvatar_MP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP.aliasID] = pAvatar_MP;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP / 9).");

			Property pAvatar_MP_Max = new Property();
			pAvatar_MP_Max.name = "MP_Max";
			pAvatar_MP_Max.properUtype = 10;
			pAvatar_MP_Max.properFlags = 4;
			pAvatar_MP_Max.aliasID = 7;
			Int32 Avatar_MP_Max_defval;
			Int32.TryParse("120", out Avatar_MP_Max_defval);
			pAvatar_MP_Max.defaultVal = Avatar_MP_Max_defval;
			pAvatarModule.propertys["MP_Max"] = pAvatar_MP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP_Max.aliasID] = pAvatar_MP_Max;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP_Max / 10).");

			Property pAvatar_attack = new Property();
			pAvatar_attack.name = "attack";
			pAvatar_attack.properUtype = 6;
			pAvatar_attack.properFlags = 4;
			pAvatar_attack.aliasID = 8;
			Int32 Avatar_attack_defval;
			Int32.TryParse("", out Avatar_attack_defval);
			pAvatar_attack.defaultVal = Avatar_attack_defval;
			pAvatarModule.propertys["attack"] = pAvatar_attack; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_attack.aliasID] = pAvatar_attack;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(attack / 6).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 5;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 9;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 5).");

			Property pAvatar_state = new Property();
			pAvatar_state.name = "state";
			pAvatar_state.properUtype = 11;
			pAvatar_state.properFlags = 4;
			pAvatar_state.aliasID = 10;
			SByte Avatar_state_defval;
			SByte.TryParse("0", out Avatar_state_defval);
			pAvatar_state.defaultVal = Avatar_state_defval;
			pAvatarModule.propertys["state"] = pAvatar_state; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_state.aliasID] = pAvatar_state;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(state / 11).");

			List<DATATYPE_BASE> pAvatar_onDialog_args = new List<DATATYPE_BASE>();
			pAvatar_onDialog_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onDialog_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_onDialog = new Method();
			pAvatar_onDialog.name = "onDialog";
			pAvatar_onDialog.methodUtype = 24;
			pAvatar_onDialog.aliasID = 1;
			pAvatar_onDialog.args = pAvatar_onDialog_args;

			pAvatarModule.methods["onDialog"] = pAvatar_onDialog; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onDialog.aliasID] = pAvatar_onDialog;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onDialog / 24).");

			List<DATATYPE_BASE> pAvatar_onJump_args = new List<DATATYPE_BASE>();

			Method pAvatar_onJump = new Method();
			pAvatar_onJump.name = "onJump";
			pAvatar_onJump.methodUtype = 23;
			pAvatar_onJump.aliasID = 2;
			pAvatar_onJump.args = pAvatar_onJump_args;

			pAvatarModule.methods["onJump"] = pAvatar_onJump; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onJump.aliasID] = pAvatar_onJump;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onJump / 23).");

			List<DATATYPE_BASE> pAvatar_dialog_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_dialog = new Method();
			pAvatar_dialog.name = "dialog";
			pAvatar_dialog.methodUtype = 21;
			pAvatar_dialog.aliasID = -1;
			pAvatar_dialog.args = pAvatar_dialog_args;

			pAvatarModule.methods["dialog"] = pAvatar_dialog; 
			pAvatarModule.cell_methods["dialog"] = pAvatar_dialog;

			pAvatarModule.idcell_methods[pAvatar_dialog.methodUtype] = pAvatar_dialog;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog / 21).");

			List<DATATYPE_BASE> pAvatar_jump_args = new List<DATATYPE_BASE>();

			Method pAvatar_jump = new Method();
			pAvatar_jump.name = "jump";
			pAvatar_jump.methodUtype = 16;
			pAvatar_jump.aliasID = -1;
			pAvatar_jump.args = pAvatar_jump_args;

			pAvatarModule.methods["jump"] = pAvatar_jump; 
			pAvatarModule.cell_methods["jump"] = pAvatar_jump;

			pAvatarModule.idcell_methods[pAvatar_jump.methodUtype] = pAvatar_jump;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jump / 16).");

			List<DATATYPE_BASE> pAvatar_relive_args = new List<DATATYPE_BASE>();

			Method pAvatar_relive = new Method();
			pAvatar_relive.name = "relive";
			pAvatar_relive.methodUtype = 15;
			pAvatar_relive.aliasID = -1;
			pAvatar_relive.args = pAvatar_relive_args;

			pAvatarModule.methods["relive"] = pAvatar_relive; 
			pAvatarModule.cell_methods["relive"] = pAvatar_relive;

			pAvatarModule.idcell_methods[pAvatar_relive.methodUtype] = pAvatar_relive;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(relive / 15).");

			List<DATATYPE_BASE> pAvatar_useSkill_args = new List<DATATYPE_BASE>();
			pAvatar_useSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_useSkill_args.Add(EntityDef.id2datatypes[6]);

			Method pAvatar_useSkill = new Method();
			pAvatar_useSkill.name = "useSkill";
			pAvatar_useSkill.methodUtype = 13;
			pAvatar_useSkill.aliasID = -1;
			pAvatar_useSkill.args = pAvatar_useSkill_args;

			pAvatarModule.methods["useSkill"] = pAvatar_useSkill; 
			pAvatarModule.cell_methods["useSkill"] = pAvatar_useSkill;

			pAvatarModule.idcell_methods[pAvatar_useSkill.methodUtype] = pAvatar_useSkill;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(useSkill / 13).");

			ScriptModule pNPCModule = new ScriptModule("NPC");
			EntityDef.moduledefs["NPC"] = pNPCModule;
			EntityDef.idmoduledefs[5] = pNPCModule;

			Property pNPC_position = new Property();
			pNPC_position.name = "position";
			pNPC_position.properUtype = 40000;
			pNPC_position.properFlags = 4;
			pNPC_position.aliasID = 1;
			KBVector3 NPC_position_defval = new KBVector3();
			pNPC_position.defaultVal = NPC_position_defval;
			pNPCModule.propertys["position"] = pNPC_position; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_position.aliasID] = pNPC_position;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(position / 40000).");

			Property pNPC_direction = new Property();
			pNPC_direction.name = "direction";
			pNPC_direction.properUtype = 40001;
			pNPC_direction.properFlags = 4;
			pNPC_direction.aliasID = 2;
			KBVector3 NPC_direction_defval = new KBVector3();
			pNPC_direction.defaultVal = NPC_direction_defval;
			pNPCModule.propertys["direction"] = pNPC_direction; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_direction.aliasID] = pNPC_direction;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(direction / 40001).");

			Property pNPC_spaceID = new Property();
			pNPC_spaceID.name = "spaceID";
			pNPC_spaceID.properUtype = 40002;
			pNPC_spaceID.properFlags = 16;
			pNPC_spaceID.aliasID = 3;
			UInt32 NPC_spaceID_defval;
			UInt32.TryParse("", out NPC_spaceID_defval);
			pNPC_spaceID.defaultVal = NPC_spaceID_defval;
			pNPCModule.propertys["spaceID"] = pNPC_spaceID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_spaceID.aliasID] = pNPC_spaceID;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(spaceID / 40002).");

			Property pNPC_eid = new Property();
			pNPC_eid.name = "eid";
			pNPC_eid.properUtype = 13;
			pNPC_eid.properFlags = 4;
			pNPC_eid.aliasID = 4;
			string NPC_eid_defval = "";
			pNPC_eid.defaultVal = NPC_eid_defval;
			pNPCModule.propertys["eid"] = pNPC_eid; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_eid.aliasID] = pNPC_eid;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(eid / 13).");

			Property pNPC_motion = new Property();
			pNPC_motion.name = "motion";
			pNPC_motion.properUtype = 15;
			pNPC_motion.properFlags = 157;
			pNPC_motion.aliasID = 5;
			pNPCModule.propertys["motion"] = pNPC_motion; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_motion.aliasID] = pNPC_motion;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(motion / 15).");

			Property pNPC_name = new Property();
			pNPC_name.name = "name";
			pNPC_name.properUtype = 12;
			pNPC_name.properFlags = 4;
			pNPC_name.aliasID = 6;
			string NPC_name_defval = "";
			pNPC_name.defaultVal = NPC_name_defval;
			pNPCModule.propertys["name"] = pNPC_name; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_name.aliasID] = pNPC_name;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(name / 12).");

			pNPCModule.useMethodDescrAlias = true;
			ScriptModule pMotionModule = new ScriptModule("Motion");
			EntityDef.moduledefs["Motion"] = pMotionModule;
			EntityDef.idmoduledefs[6] = pMotionModule;

			Property pMotion_position = new Property();
			pMotion_position.name = "position";
			pMotion_position.properUtype = 40000;
			pMotion_position.properFlags = 4;
			pMotion_position.aliasID = 1;
			KBVector3 Motion_position_defval = new KBVector3();
			pMotion_position.defaultVal = Motion_position_defval;
			pMotionModule.propertys["position"] = pMotion_position; 

			pMotionModule.usePropertyDescrAlias = true;
			pMotionModule.idpropertys[(UInt16)pMotion_position.aliasID] = pMotion_position;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Motion), property(position / 40000).");

			Property pMotion_direction = new Property();
			pMotion_direction.name = "direction";
			pMotion_direction.properUtype = 40001;
			pMotion_direction.properFlags = 4;
			pMotion_direction.aliasID = 2;
			KBVector3 Motion_direction_defval = new KBVector3();
			pMotion_direction.defaultVal = Motion_direction_defval;
			pMotionModule.propertys["direction"] = pMotion_direction; 

			pMotionModule.usePropertyDescrAlias = true;
			pMotionModule.idpropertys[(UInt16)pMotion_direction.aliasID] = pMotion_direction;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Motion), property(direction / 40001).");

			Property pMotion_spaceID = new Property();
			pMotion_spaceID.name = "spaceID";
			pMotion_spaceID.properUtype = 40002;
			pMotion_spaceID.properFlags = 16;
			pMotion_spaceID.aliasID = 3;
			UInt32 Motion_spaceID_defval;
			UInt32.TryParse("", out Motion_spaceID_defval);
			pMotion_spaceID.defaultVal = Motion_spaceID_defval;
			pMotionModule.propertys["spaceID"] = pMotion_spaceID; 

			pMotionModule.usePropertyDescrAlias = true;
			pMotionModule.idpropertys[(UInt16)pMotion_spaceID.aliasID] = pMotion_spaceID;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Motion), property(spaceID / 40002).");

			Property pMotion_moveSpeed = new Property();
			pMotion_moveSpeed.name = "moveSpeed";
			pMotion_moveSpeed.properUtype = 16;
			pMotion_moveSpeed.properFlags = 4;
			pMotion_moveSpeed.aliasID = 4;
			Byte Motion_moveSpeed_defval;
			Byte.TryParse("5", out Motion_moveSpeed_defval);
			pMotion_moveSpeed.defaultVal = Motion_moveSpeed_defval;
			pMotionModule.propertys["moveSpeed"] = pMotion_moveSpeed; 

			pMotionModule.usePropertyDescrAlias = true;
			pMotionModule.idpropertys[(UInt16)pMotion_moveSpeed.aliasID] = pMotion_moveSpeed;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Motion), property(moveSpeed / 16).");

			pMotionModule.useMethodDescrAlias = true;
			ScriptModule pMonsterModule = new ScriptModule("Monster");
			EntityDef.moduledefs["Monster"] = pMonsterModule;
			EntityDef.idmoduledefs[7] = pMonsterModule;

			Property pMonster_position = new Property();
			pMonster_position.name = "position";
			pMonster_position.properUtype = 40000;
			pMonster_position.properFlags = 4;
			pMonster_position.aliasID = 1;
			KBVector3 Monster_position_defval = new KBVector3();
			pMonster_position.defaultVal = Monster_position_defval;
			pMonsterModule.propertys["position"] = pMonster_position; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_position.aliasID] = pMonster_position;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(position / 40000).");

			Property pMonster_direction = new Property();
			pMonster_direction.name = "direction";
			pMonster_direction.properUtype = 40001;
			pMonster_direction.properFlags = 4;
			pMonster_direction.aliasID = 2;
			KBVector3 Monster_direction_defval = new KBVector3();
			pMonster_direction.defaultVal = Monster_direction_defval;
			pMonsterModule.propertys["direction"] = pMonster_direction; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_direction.aliasID] = pMonster_direction;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(direction / 40001).");

			Property pMonster_spaceID = new Property();
			pMonster_spaceID.name = "spaceID";
			pMonster_spaceID.properUtype = 40002;
			pMonster_spaceID.properFlags = 16;
			pMonster_spaceID.aliasID = 3;
			UInt32 Monster_spaceID_defval;
			UInt32.TryParse("", out Monster_spaceID_defval);
			pMonster_spaceID.defaultVal = Monster_spaceID_defval;
			pMonsterModule.propertys["spaceID"] = pMonster_spaceID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_spaceID.aliasID] = pMonster_spaceID;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(spaceID / 40002).");

			Property pMonster_HP = new Property();
			pMonster_HP.name = "HP";
			pMonster_HP.properUtype = 21;
			pMonster_HP.properFlags = 4;
			pMonster_HP.aliasID = 4;
			Int32 Monster_HP_defval;
			Int32.TryParse("100", out Monster_HP_defval);
			pMonster_HP.defaultVal = Monster_HP_defval;
			pMonsterModule.propertys["HP"] = pMonster_HP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP.aliasID] = pMonster_HP;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP / 21).");

			Property pMonster_HP_Max = new Property();
			pMonster_HP_Max.name = "HP_Max";
			pMonster_HP_Max.properUtype = 22;
			pMonster_HP_Max.properFlags = 4;
			pMonster_HP_Max.aliasID = 5;
			Int32 Monster_HP_Max_defval;
			Int32.TryParse("100", out Monster_HP_Max_defval);
			pMonster_HP_Max.defaultVal = Monster_HP_Max_defval;
			pMonsterModule.propertys["HP_Max"] = pMonster_HP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP_Max.aliasID] = pMonster_HP_Max;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP_Max / 22).");

			Property pMonster_MP = new Property();
			pMonster_MP.name = "MP";
			pMonster_MP.properUtype = 23;
			pMonster_MP.properFlags = 4;
			pMonster_MP.aliasID = 6;
			Int32 Monster_MP_defval;
			Int32.TryParse("120", out Monster_MP_defval);
			pMonster_MP.defaultVal = Monster_MP_defval;
			pMonsterModule.propertys["MP"] = pMonster_MP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP.aliasID] = pMonster_MP;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP / 23).");

			Property pMonster_MP_Max = new Property();
			pMonster_MP_Max.name = "MP_Max";
			pMonster_MP_Max.properUtype = 24;
			pMonster_MP_Max.properFlags = 4;
			pMonster_MP_Max.aliasID = 7;
			Int32 Monster_MP_Max_defval;
			Int32.TryParse("120", out Monster_MP_Max_defval);
			pMonster_MP_Max.defaultVal = Monster_MP_Max_defval;
			pMonsterModule.propertys["MP_Max"] = pMonster_MP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP_Max.aliasID] = pMonster_MP_Max;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP_Max / 24).");

			Property pMonster_eid = new Property();
			pMonster_eid.name = "eid";
			pMonster_eid.properUtype = 19;
			pMonster_eid.properFlags = 4;
			pMonster_eid.aliasID = 8;
			string Monster_eid_defval = "";
			pMonster_eid.defaultVal = Monster_eid_defval;
			pMonsterModule.propertys["eid"] = pMonster_eid; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_eid.aliasID] = pMonster_eid;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(eid / 19).");

			Property pMonster_motion = new Property();
			pMonster_motion.name = "motion";
			pMonster_motion.properUtype = 26;
			pMonster_motion.properFlags = 157;
			pMonster_motion.aliasID = 9;
			pMonsterModule.propertys["motion"] = pMonster_motion; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_motion.aliasID] = pMonster_motion;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(motion / 26).");

			Property pMonster_name = new Property();
			pMonster_name.name = "name";
			pMonster_name.properUtype = 18;
			pMonster_name.properFlags = 4;
			pMonster_name.aliasID = 10;
			string Monster_name_defval = "";
			pMonster_name.defaultVal = Monster_name_defval;
			pMonsterModule.propertys["name"] = pMonster_name; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_name.aliasID] = pMonster_name;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(name / 18).");

			Property pMonster_state = new Property();
			pMonster_state.name = "state";
			pMonster_state.properUtype = 20;
			pMonster_state.properFlags = 4;
			pMonster_state.aliasID = 11;
			SByte Monster_state_defval;
			SByte.TryParse("0", out Monster_state_defval);
			pMonster_state.defaultVal = Monster_state_defval;
			pMonsterModule.propertys["state"] = pMonster_state; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_state.aliasID] = pMonster_state;

			//KBELog.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(state / 20).");

			pMonsterModule.useMethodDescrAlias = true;
		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "DBID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "AnonymousArray_22";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "AnonymousArray_23";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "AnonymousArray_24";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}