/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/NPC.def
	public class EntityBaseEntityCall_NPCBase : EntityCall
	{
		public EntityBaseEntityCall_MotionBase motion = null;

		public EntityBaseEntityCall_NPCBase(Int32 eid, string ename) : base(eid, ename)
		{
			motion = new EntityBaseEntityCall_MotionBase(15, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_NPCBase : EntityCall
	{
		public EntityCellEntityCall_MotionBase motion = null;

		public EntityCellEntityCall_NPCBase(Int32 eid, string ename) : base(eid, ename)
		{
			motion = new EntityCellEntityCall_MotionBase(15, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
