/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void dialog(Int32 arg1, string arg2)
		{
			Bundle pBundle = newCall("dialog", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void jump()
		{
			Bundle pBundle = newCall("jump", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void relive()
		{
			Bundle pBundle = newCall("relive", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void useSkill(Int32 arg1, SByte arg2)
		{
			Bundle pBundle = newCall("useSkill", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt8(arg2);
			sendCall(null);
		}

	}
	}
