/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Monster.def
	public class EntityBaseEntityCall_MonsterBase : EntityCall
	{
		public EntityBaseEntityCall_MotionBase motion = null;

		public EntityBaseEntityCall_MonsterBase(Int32 eid, string ename) : base(eid, ename)
		{
			motion = new EntityBaseEntityCall_MotionBase(27, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_MonsterBase : EntityCall
	{
		public EntityCellEntityCall_MotionBase motion = null;

		public EntityCellEntityCall_MonsterBase(Int32 eid, string ename) : base(eid, ename)
		{
			motion = new EntityCellEntityCall_MotionBase(27, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
