/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class NPC : NPCBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/NPC.def
	// Please inherit and implement "class NPC : NPCBase"
	public abstract class NPCBase : Entity
	{
		public EntityBaseEntityCall_NPCBase baseEntityCall = null;
		public EntityCellEntityCall_NPCBase cellEntityCall = null;

		public string eid = "";
		public virtual void onEidChanged(string oldValue) {}
		public MotionBase motion = null;
		public string name = "";
		public virtual void onNameChanged(string oldValue) {}


		public NPCBase()
		{
			foreach (System.Reflection.Assembly ass in AppDomain.CurrentDomain.GetAssemblies())
			{
				Type entityComponentScript = ass.GetType("KBEngine.Motion");
				if(entityComponentScript != null)
				{
					motion = (MotionBase)Activator.CreateInstance(entityComponentScript);
					motion.owner = this;
					motion.entityComponentPropertyID = 15;
					motion.name_ = "Motion";
				}
			}

			if(motion == null)
				throw new Exception("Please inherit and implement, such as: \"class Motion : MotionBase\"");

		}

		public override void onComponentsEnterworld()
		{
			motion.onEnterworld();
		}

		public override void onComponentsLeaveworld()
		{
			motion.onLeaveworld();
		}

		public override List<EntityComponent> getComponents(string componentName, bool all)
		{
			List<EntityComponent> founds = new List<EntityComponent>();

			if (motion.name_ == componentName)
			{
				founds.Add(motion);
				if (!all)
					return founds;
			}

			return founds;
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_NPCBase(id, className);
			motion.onGetBase();
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_NPCBase(id, className);
			motion.onGetCell();
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
			motion.onLoseCell();
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
			motion.onAttached(this);
		}

		public override void detachComponents()
		{
			motion.onDetached(this);
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["NPC"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					case 15:
						motion.onRemoteMethodCall(methodUtype, stream);
						break;
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["NPC"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						case 15:
							motion.onUpdatePropertys(_t_child_utype, stream, -1);
							break;
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 40001:
						KBVector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 13:
						string oldval_eid = eid;
						eid = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onEidChanged(oldval_eid);
						}
						else
						{
							if(inWorld)
								onEidChanged(oldval_eid);
						}

						break;
					case 15:
						motion.createFromStream(stream);
						break;
					case 12:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						KBVector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["NPC"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			KBVector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			string oldval_eid = eid;
			Property prop_eid = pdatas[4];
			if(prop_eid.isBase())
			{
				if(inited && !inWorld)
					onEidChanged(oldval_eid);
			}
			else
			{
				if(inWorld)
				{
					if(prop_eid.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onEidChanged(oldval_eid);
					}
				}
			}

			motion.callPropertysSetMethods();

			string oldval_name = name;
			Property prop_name = pdatas[6];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			KBVector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
}